import java.util.ArrayList;


public class Acronyms {
    public String acronize(String[] document) {
        ArrayList<String> a = new ArrayList<String>();

        int c = 0, count = 0;
        for (int i = 0; i < document.length; i++) {
            String[] tokens = document[i].split(" ");
            for (int k = 0; k < tokens.length; k++) {
                a.add(tokens[k]);
            }
        }
        String s = "";
        for (int j = 1; j < a.size(); j++) {
            System.out.println(a.get(j).charAt(0));
            if (Character.isUpperCase(a.get(j).charAt(0))) {
                c = 1;
                count++;
                s = s + a.get(j).charAt(0);
            } else if (c == 1) {
                c = 0;
                count++;
            } else {
                count--;
                if(! Character.isLetter(a.get(j).charAt((a.get(j)).length()-1)) )    {
                    s= s+a.get(j).charAt((a.get(j)).length()-1);
                }
                a.remove(j - count);
                a.add(j - count, s);
                for (int i = 1; i < count; i++)
                    a.remove(j - count + i);
            }

        }
        return a.toString();

    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String p1) {
        System.out.print("Test " + testNum + ": [" + "{");
        for (int i = 0; p0.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print("\"" + p0[i] + "\"");
        }
        System.out.print("}");
        System.out.println("]");
        Acronyms obj;
        String answer;
        obj = new Acronyms();
        long startTime = System.currentTimeMillis();
        answer = obj.acronize(p0);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + "\"" + p1 + "\"");
        }
        System.out.println("Your answer:");
        System.out.println("\t" + "\"" + answer + "\"");
        if (hasAnswer) {
            res = answer.equals(p1);
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }

    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        String[] p0;
        String p1;

        // ----- test 0 -----
        p0 = new String[]{"We the people of the United States of America."};
        p1 = "We the people of the USA.";
        all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = new String[]{"Don't", "worry.", "Be", "Happy!"};
        p1 = "Don't worry. BH!";
        all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = new String[]{"Entering contests at TopCoder, Inc.", "is a good way to develop your skills."};
        p1 = "Entering contests at TCI. is a good way to develop your skills.";
        all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = new String[]{"Working at the United States Postal Service", "in the United States of America", "is a satisfying experience."};
        p1 = "Working at the USPS in the USA is a satisfying experience.";
        all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
        // ------------------

        // ----- test 4 -----
        p0 = new String[]{"a A & a & a B"};
        p1 = "a A & a & a B";
        all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
        // ------------------

        // ----- test 5 -----
        p0 = new String[]{"The First word can't be included.  In", "A sequence, that is."};
        p1 = "The First word can't be included.  In A sequence, that is.";
        all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
        // ------------------

        // ----- test 6 -----
        p0 = new String[]{"A Test & Test & & TEst"};
        p1 = "A TT & & TEst";
        all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
        // ------------------

        // ----- test 7 -----
        p0 = new String[]{"This is a TEST tEST Test. ", ".Go Test"};
        p1 = "This is a TESTT.  .Go Test";
        all_right = KawigiEdit_RunTest(7, p0, true, p1) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // PROBLEM STATEMENT
    // Acronyms are commonly used to make documents more concise.  Your task in this problem is to develop a program that automates the conversion of sequences of words into acronyms in a String[], document.  A sequence of words must meet all of the following criteria before it can be converted to an acronym:
    //
    // The words in the sequence must all be within one sentence.
    // The sequence must not include the first word in a sentence.
    // At least two words in the sequence must begin with uppercase letters.
    // The first and last words in the sequence must begin with uppercase letters.
    // There may not be two adjacent words that do not begin with uppercase letters in the sequence.
    // The sequence must be as long as possible.  It may not be a subsequence of any longer sequence meeting the five criteria above.
    //
    // A word is defined as a sequence of characters surrounded on both sides by spaces or edges of the element of document.  Note that a word may include non-letter characters.  A new sentence, in this problem, always starts at the beginning of the input and after two consecutive spaces, where a new line (new element of document) counts as one space.
    // For each sequence of words meeting the criteria as defined above, you should convert it to an acronym by replacing the whole sequence of words with all the uppercase letters in the words that start with uppercase letters (in order).  The only caveat to this is that if there are non-letter characters at the end of the last word in the sequence, you should not replace them.
    //
    // For example, "TopCoder, Inc." would become "TCI.".  Note that the '.' at the end of "Inc." remains in the acronym but the ',' at the end of "TopCoder," is removed.  Also, "United States of America" would be converted to "USA"; there is no 'o' because "of" does not start with an uppercase letter.
    //
    // After inserting the acronyms, you should return a String representing the entire document.  A new line in the input always counts as one space, and this should be represented in the output.
    //
    // DEFINITION
    // Class:Acronyms
    // Method:acronize
    // Parameters:String[]
    // Returns:String
    // Method signature:String acronize(String[] document)
    //
    //
    // NOTES
    // -Since new lines count as spaces, the input is identical in function to a single String that is the concatenation of all the elements of document with single spaces inserted between them.
    //
    //
    // CONSTRAINTS
    // -document will contain between 1 and 50 elements, inclusive.
    // -Each element of document will contain between 1 and 50 characters, inclusive.
    // -Each character in document will have ASCII values between 32 and 122 inclusive.
    // -No element of document will have leading spaces.
    // -No element of document will have more than one trailing space.
    // -The last element of document will not have trailing spaces.
    // -There will not be two adjacent non-letter characters other than spaces.
    // -There will never be more than 2 consecutive spaces in document
    //
    //
    // EXAMPLES
    //
    // 0)
    // {"We the people of the United States of America."}
    //
    // Returns: "We the people of the USA."
    //
    // "of" is not include in the acronym since it starts with a lowercase letter.
    //
    // 1)
    // {"Don't","worry.","Be","Happy!"}
    //
    // Returns: "Don't worry. BH!"
    //
    // Even though there is a period, there is only one sentence according to the rules of this problem.
    //
    // 2)
    // {"Entering contests at TopCoder, Inc.", "is a good way to develop your skills."}
    //
    // Returns: "Entering contests at TCI. is a good way to develop your skills."
    //
    // Be sure to include the period after "TCI" in your return.
    //
    // 3)
    // {"Working at the United States Postal Service",
    //  "in the United States of America",
    //  "is a satisfying experience."}
    //
    // Returns: "Working at the USPS in the USA is a satisfying experience."
    //
    // 4)
    // {"a A & a & a B"}
    //
    // Returns: "a A & a & a B"
    //
    // 5)
    // {"The First word can't be included.  In","A sequence, that is."}
    //
    // Returns: "The First word can't be included.  In A sequence, that is."
    //
    // "The" and "In" are both the first words in sentences.
    //
    // 6)
    // {"A Test & Test & & TEst"}
    //
    // Returns: "A TT & & TEst"
    //
    // Note that "&" counts as a word.
    //
    // 7)
    // {"This is a TEST tEST Test. ", ".Go Test"}
    //
    // Returns: "This is a TESTT.  .Go Test"
    //
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
