import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class BinPackingEasy
{
	public int minBins(int[] item)
	{
        int l=item.length;
        int count=0;
		Arrays.sort(item);
        int here=l-1;
       outer: for(int i=0;i<here;i++)
        {
            for(int j= here;j>i;j--)
            {
               if(item[i]+item[j]<=300)
               {  count++;
                here=j-1; continue outer;}
            }

        }
        return (l-count);
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}");
		System.out.println("]");
		BinPackingEasy obj;
		int answer;
		obj = new BinPackingEasy();
		long startTime = System.currentTimeMillis();
		answer = obj.minBins(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int p1;
		
		// ----- test 0 -----
		p0 = new int[]{150,150,150,150,150};
		p1 = 3;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{130,140,150,160};
		p1 = 2;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{300, 101, 200};
		p1 = 3;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{101,200,101,101,101,101,200,101,200};
		p1 = 6;
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{123,145,167,213,245,267,289,132,154,176,198};
		p1 = 8;
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Fox Ciel has some items. The weight of the i-th (0-based) item is item[i]. She wants to put all items into bins.
	// 
	// 
	// The capacity of each bin is 300. She can put an arbitrary number of items into a single bin, but the total weight of items in a bin must be less than or equal to 300.
	// 
	// 
	// You are given the int[] item. It is known that the weight of each item is between 101 and 300, inclusive. Return the minimal number of bins required to store all items.
	// 
	// DEFINITION
	// Class:BinPackingEasy
	// Method:minBins
	// Parameters:int[]
	// Returns:int
	// Method signature:int minBins(int[] item)
	// 
	// 
	// CONSTRAINTS
	// -item will contain between 1 and 50 elements, inclusive.
	// -Each element of item will be between 101 and 300, inclusive.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// {150, 150, 150, 150, 150}
	// 
	// Returns: 3
	// 
	// You have five items and each bin can hold at most two of them. You need at least three bins.
	// 
	// 1)
	// {130, 140, 150, 160}
	// 
	// Returns: 2
	// 
	// For example, you can distribute the items in the following way:
	// 
	// Bin 1: 130, 150
	// Bin 2: 140, 160
	// 
	// 
	// 
	// 2)
	// {101, 101, 101, 101, 101, 101, 101, 101, 101}
	// 
	// Returns: 5
	// 
	// 
	// 
	// 3)
	// {101, 200, 101, 101, 101, 101, 200, 101, 200}
	// 
	// Returns: 6
	// 
	// 
	// 
	// 4)
	// {123, 145, 167, 213, 245, 267, 289, 132, 154, 176, 198}
	// 
	// Returns: 8
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
