import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class CrossingTheRiver
{
    class Points{
        int x,y;
        Points(int a,int b){
            x=a;y=b;
        }
    }
	public String isItEvenPossible(int waterWidth, int landWidth, int[] blockHeight, int depth)
	{
		int l=blockHeight.length;
                       ArrayList<Points> a=new ArrayList<Points>();
        if(l<waterWidth+landWidth)
            return "IMPOSSIBLE";

        Arrays.sort(blockHeight);
        for(int i=0;i<l;i++)
        {
            for(int j=i+1;j<l;j++)
            {
                if (blockHeight[j]-blockHeight[i]<=1){
                    a.add(new Points(i,j));
                }
            }
        }


        for(int i=0;i<a.size();i++)
        {
            int s1=a.get(i).x;
            int s2=a.get(i).y;
            for(int k=s1;k<s2;k++)
            {

            }
        }
        if(blockHeight[0]-(blockHeight[l-waterWidth-1]-depth)>1)
            return "IMPOSSIBLE" ;
        else
            return "POSSIBLE";
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int[] p2, int p3, boolean hasAnswer, String p4) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p2[i]);
		}
		System.out.print("}" + "," + p3);
		System.out.println("]");
		CrossingTheRiver obj;
		String answer;
		obj = new CrossingTheRiver();
		long startTime = System.currentTimeMillis();
		answer = obj.isItEvenPossible(p0, p1, p2, p3);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p4 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p4);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		int[] p2;
		int p3;
		String p4;
		
		// ----- test 0 -----
		p0 = 3;
		p1 = 3;
		p2 = new int[]{3,4,4,5,5,6};
		p3 = 2;
		p4 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 3;
		p1 = 3;
		p2 = new int[]{3,4,4,5,6,6};
		p3 = 2;
		p4 = "IMPOSSIBLE";
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 5;
		p1 = 2;
		p2 = new int[]{4,4,4,4,4};
		p3 = 4;
		p4 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 5;
		p1 = 5;
		p2 = new int[]{5,5,5,5,5,5,2,3,4,4,6,7,3,2};
		p3 = 2;
		p4 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 5;
		p1 = 7;
		p2 = new int[]{6,6,6,6,6,6,6,6,6,6,6,6,7,8,9,10};
		p3 = 5;
		p4 = "POSSIBLE";
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = 1;
		p1 = 1;
		p2 = new int[]{5,3,4};
		p3 = 2;
		p4 = "IMPOSSIBLE";
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// NOTE: This problem statement contains images that may not display properly if viewed outside of the applet.
	// 
	// You start on the left side of a river. The river is waterWidth units wide and infinitely deep. The land on the right side of the river is (landWidth+1) units wide. On the far right side of this land there is an infinitely tall ladder of width 1 unit. 
	// 
	// You own many blocks specified by the int[], blockHeight. The i-th block has a width of 1 unit and a height of blockHeight[i] units. You have observed that all of the blocks have the curious property that when placed in water they float vertically with exactly depth units below the surface of the water (see image below). Blocks on land or in the water must be placed vertically. A side of the block that is 1 unit wide must touch the ground or be submerged in water. You can not place blocks to the left of the river. You also can not place blocks on top of other blocks.
	// 
	// Your objective is to cross the river and reach the ladder. After placing the blocks, you have three allowed movements: You can move to the right if height of the top of the next block (or the height of the land if there is no block there) is the same as your current height. You can also climb to the right if the height of the next block is exactly one unit above your current height. Finally, the ladder can always be reached no matter at what height you are when standing immediately to its left. It would be too dangerous to move down to a block or the land that lies at a lower height. Also, the water is too cold and you cannot swim.
	// 
	// 
	// 
	// If it is possible to place the available blocks such that you can reach the ladder then return the String "POSSIBLE" (quotes for clarity). If it is not possible then return the String "IMPOSSIBLE".
	// 
	// DEFINITION
	// Class:CrossingTheRiver
	// Method:isItEvenPossible
	// Parameters:int, int, int[], int
	// Returns:String
	// Method signature:String isItEvenPossible(int waterWidth, int landWidth, int[] blockHeight, int depth)
	// 
	// 
	// CONSTRAINTS
	// -waterWidth will be between 1 and 50, inclusive.
	// -landWidth will be between 1 and 50, inclusive.
	// -blockHeight will contain between waterWidth and 50 elements, inclusive.
	// -depth will be between 2 and 100, inclusive.
	// -Each element of blockHeight will be between depth and 100, inclusive.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// 3
	// 3
	// {3,4,4,5,5, 6}
	// 2
	// 
	// Returns: "POSSIBLE"
	// 
	// The following image describes a possible solution:
	// 
	// 
	// 1)
	// 3
	// 3
	// {3,4,4,5,6, 6}
	// 2
	// 
	// Returns: "IMPOSSIBLE"
	// 
	// 
	// 
	// 2)
	// 5
	// 2
	// {4,4,4,4,4}
	// 4
	// 
	// Returns: "POSSIBLE"
	// 
	// It is not always necessary to place blocks on the land.
	// 
	// 
	// 3)
	// 5
	// 5
	// {5,5,5,5,5,5, 2,3,4,4,6, 7, 3, 2}
	// 2
	// 
	// Returns: "POSSIBLE"
	// 
	// A possible solution is described by the image in the problem statement.
	// 
	// 4)
	// 5
	// 7
	// {6,6,6,6,6,6,6, 6,6,6,6,6,7,8,9,10}
	// 5
	// 
	// Returns: "POSSIBLE"
	// 
	// 
	// 
	// 5)
	// 1
	// 1
	// {5,3,4}
	// 2
	// 
	// Returns: "IMPOSSIBLE"
	// 
	// Remember that it is not possible to place a block on the starting position.
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
