import com.sun.org.apache.xpath.internal.res.XPATHErrorResources_pt_BR;

import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class FlipGame
{
	public int minOperations(String[] board)
	{
		  int l=board.length;
        int m=board[0].length();
        int[][] store=new int[l][m];
        for(int i=0;i<l;i++)
        {
            String s= board[i];
            for(int j=0;j<m;j++)
            {
                     store[i][j]=s.charAt(j)-'0';
            }
        }
        return 0;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		FlipGame obj;
		int answer;
		obj = new FlipGame();
		long startTime = System.currentTimeMillis();
		answer = obj.minOperations(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p1);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		
		// ----- test 0 -----
		p0 = new String[]{"1000","1110","1111"};
		p1 = 1;
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"1111","1111","1111"};
		p1 = 1;
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"00","00","00"};
		p1 = 0;
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"00000000","00100000","01000000","00001000","00000000"};
		p1 = 4;
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"000000000000001100000000000000","000000000000011110000000000000","000000000000111111000000000000","000000000001111111100000000000","000000000011111111110000000000","000000000111111111111000000000","000000001100111111001100000000","000000011000011110000110000000","000000111100111111001111000000","000001111111111111111111100000","000011111111111111111111110000","000111111111000000111111111000","001111111111100001111111111100","011111111111110011111111111110","111111111111111111111111111111"};
		p1 = 29;
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Eel Takahashikun is playing a simple game on a rectangular board.
	// 
	// 
	// The rectangular board is divided into H x W unit squares. Each unit square contains a 0 or a 1. In each operation, Takahashikun chooses a shortest path along edges of unit squares from the upper-left corner to the lower-right corner, and flips the numbers in all unit squares that are below the chosen path (i.e., changes all 0s into 1s and vice versa).
	// 
	// 
	// For example, the following picture shows a valid operation. The squares below the chosen path are highlighted in green.
	// 
	// 
	// 
	// 
	// 
	// The operation in the following picture is invalid because the path is not shortest.
	// 
	// 
	// 
	// 
	// 
	// You are given the initial state of the board in String[] board. The j-th character of the i-th element is the number written in the unit square at row i, column j. Rows are numbered from top to bottom, and columns are numbered from left to right. Return the minimal number of iterations required to change all numbers to 0s.
	// 
	// 
	// DEFINITION
	// Class:FlipGame
	// Method:minOperations
	// Parameters:String[]
	// Returns:int
	// Method signature:int minOperations(String[] board)
	// 
	// 
	// NOTES
	// -It is always possible to change all numbers to 0s by a finite number of operations.
	// 
	// 
	// CONSTRAINTS
	// -board will contain between 1 and 50 elements, inclusive.
	// -Each element of board will contain between 1 and 50 characters, inclusive.
	// -Each element of board will contain the same number of characters.
	// -Each character in board will be '0' or '1'.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// {"1000",
	//  "1110",
	//  "1111"}
	// 
	// Returns: 1
	// 
	// Takahashikun can flip all 1s in one operation.
	// 
	// 
	// 1)
	// {"1111",
	//  "1111",
	//  "1111"}
	// 
	// Returns: 1
	// 
	// 
	// 
	// 2)
	// {"00",
	//  "00",
	//  "00"}
	// 
	// Returns: 0
	// 
	// 
	// 
	// 3)
	// {"00000000",
	//  "00100000",
	//  "01000000",
	//  "00001000",
	//  "00000000"}
	// 
	// Returns: 4
	// 
	// 
	// 
	// 4)
	// {"000000000000001100000000000000",
	//  "000000000000011110000000000000",
	//  "000000000000111111000000000000",
	//  "000000000001111111100000000000",
	//  "000000000011111111110000000000",
	//  "000000000111111111111000000000",
	//  "000000001100111111001100000000",
	//  "000000011000011110000110000000",
	//  "000000111100111111001111000000",
	//  "000001111111111111111111100000",
	//  "000011111111111111111111110000",
	//  "000111111111000000111111111000",
	//  "001111111111100001111111111100",
	//  "011111111111110011111111111110",
	//  "111111111111111111111111111111"}
	// 
	// Returns: 29
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
