public class FlowerGarden {
    public int[] getOrdering(int[] height, int[] bloom, int[] wilt) {

        int c = 0; int len=height.length;
        int[][] ans = new int[len][len]; int []flag=new int[len];int []a=new int[len];   int temp,t1,t2,max,key;
        for (int i = 0; i < len; i++) {

            for (int j = 0; j <len; j++) {

                if (isBlocking(bloom, wilt, height, i,j) == 1)
                {
                    ans[i][j]=1;
                }
                else
                    ans[i][j]=0;
            }
        }
       outer: for(int i=len-1;i>=0;i--)

        {
            if(flag[i]==1)
                continue;
            for(int j=0;j<len;j++)
            {
                if(flag[j]==1) continue;
                if(i!=j )
                {
                    if(ans[i][j]==1)
                        continue outer;
                }
            }
            flag[i]=1;
            a[c]=height[i]; c++;
            i=len-2;

        }


        return a;


    }

    int isBlocking(int[] bloom, int[] wilt, int[] height, int i, int j) {
        if (((wilt[i] >= bloom[j] && wilt[i] <= wilt[j]) && height[i]> height[j]) ||( (height[i] > height[j] && bloom[i] >= bloom[j] && bloom[i] <= wilt[j])) || (( (height[i] > height[j] && bloom[i] <= bloom[j] && wilt[i] >= wilt[j])))) {
            return 1;
        } else
            return 0;

    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
    private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, int[] p2, boolean hasAnswer, int[] p3) {
        System.out.print("Test " + testNum + ": [" + "{");
        for (int i = 0; p0.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p0[i]);
        }
        System.out.print("}" + "," + "{");
        for (int i = 0; p1.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p1[i]);
        }
        System.out.print("}" + "," + "{");
        for (int i = 0; p2.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p2[i]);
        }
        System.out.print("}");
        System.out.println("]");
        FlowerGarden obj;
        int[] answer;
        obj = new FlowerGarden();
        long startTime = System.currentTimeMillis();
        answer = obj.getOrdering(p0, p1, p2);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.print("\t" + "{");
            for (int i = 0; p3.length > i; ++i) {
                if (i > 0) {
                    System.out.print(",");
                }
                System.out.print(p3[i]);
            }
            System.out.println("}");
        }
        System.out.println("Your answer:");
        System.out.print("\t" + "{");
        for (int i = 0; answer.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(answer[i]);
        }
        System.out.println("}");
        if (hasAnswer) {
            if (answer.length != p3.length) {
                res = false;
            } else {
                for (int i = 0; answer.length > i; ++i) {
                    if (answer[i] != p3[i]) {
                        res = false;
                    }
                }
            }
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }

    public static void main(String[] args) {
        boolean all_right;
        all_right = true;

        int[] p0;
        int[] p1;
        int[] p2;
        int[] p3;

        // ----- test 0 -----
        p0 = new int[]{5, 4, 3, 2, 1};
        p1 = new int[]{1, 1, 1, 1, 1};
        p2 = new int[]{365, 365, 365, 365, 365};
        p3 = new int[]{1, 2, 3, 4, 5};
        all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
        // ------------------

        // ----- test 1 -----
        p0 = new int[]{5, 4, 3, 2, 1};
        p1 = new int[]{1, 5, 10, 15, 20};
        p2 = new int[]{4, 9, 14, 19, 24};
        p3 = new int[]{5, 4, 3, 2, 1};
        all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
        // ------------------

        // ----- test 2 -----
        p0 = new int[]{5, 4, 3, 2, 1};
        p1 = new int[]{1, 5, 10, 15, 20};
        p2 = new int[]{5, 10, 15, 20, 25};
        p3 = new int[]{1, 2, 3, 4, 5};
        all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
        // ------------------

        // ----- test 3 -----
        p0 = new int[]{5, 4, 3, 2, 1};
        p1 = new int[]{1, 5, 10, 15, 20};
        p2 = new int[]{5, 10, 14, 20, 25};
        p3 = new int[]{3, 4, 5, 1, 2};
        all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
        // ------------------

        // ----- test 4 -----
        p0 = new int[]{1, 2, 3, 4, 5, 6};
        p1 = new int[]{1, 3, 1, 3, 1, 3};
        p2 = new int[]{2, 4, 2, 4, 2, 4};
        p3 = new int[]{2, 4, 6, 1, 3, 5};
        all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
        // ------------------

        // ----- test 5 -----
        p0 = new int[]{3, 2, 5, 4};
        p1 = new int[]{1, 2, 11, 10};
        p2 = new int[]{4, 3, 12, 13};
        p3 = new int[]{4, 5, 2, 3};
        all_right = KawigiEdit_RunTest(5, p0, p1, p2, true, p3) && all_right;
        // ------------------

        if (all_right) {
            System.out.println("You're a stud (at least on the example cases)!");
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // PROBLEM STATEMENT
    //
    // You are planting a flower garden with bulbs to give you joyous flowers throughout the year.  However, you wish to plant the flowers such that they do not block other flowers while they are visible.
    //
    //
    //
    // You will be given a int[] height, a int[] bloom, and a int[] wilt.  Each type of flower is represented by the element at the same index of height, bloom, and wilt.  height represents how high each type of flower grows, bloom represents the morning that each type of flower springs from the ground, and wilt represents the evening that each type of flower shrivels up and dies.  Each element in bloom and wilt will be a number between 1 and 365 inclusive, and wilt[i] will always be greater than bloom[i].  You must plant all of the flowers of the same type in a single row for appearance, and you also want to have the flowers in rows which are more towards the front be as tall as possible.  However, if a flower type is taller than another type, and both types can be out of the ground at the same time, the shorter flower must be planted in front of the taller flower to prevent blocking.  A flower blooms in the morning, and wilts in the evening, so even if one flower is blooming on the same day another flower is wilting, one can block the other.
    //
    //
    //
    // For example, if your garden of flowers has heights 1, 2, and 3, and the flowers of height 3 bloom and wilt with flowers of height 1, but neither conflicts with 2, your best arrangement would be 2,1,3.  1,3,2 would be possible, but then the first row of flowers is shorter, which is less desirable.
    //
    //
    //
    // You should return a int[] which contains the elements of height in the order you should plant your flowers to acheive the above goals.  The front of the garden is represented by the first element in your return value, and is where you view the garden from.  The elements of height will all be unique, so there will always be a well-defined ordering.
    //
    //
    // DEFINITION
    // Class:FlowerGarden
    // Method:getOrdering
    // Parameters:int[], int[], int[]
    // Returns:int[]
    // Method signature:int[] getOrdering(int[] height, int[] bloom, int[] wilt)
    //
    //
    // CONSTRAINTS
    // -height will have between 2 and 50 elements, inclusive.
    // -bloom will have the same number of elements as height
    // -wilt will have the same number of elements as height
    // -height will have no repeated elements.
    // -Each element of height will be between 1 and 1000, inclusive.
    // -Each element of bloom will be between 1 and 365, inclusive.
    // -Each element of wilt will be between 1 and 365, inclusive.
    // -For each element i of bloom and wilt, wilt[i] will be greater than bloom[i].
    //
    //
    // EXAMPLES
    //
    // 0)
    // {5,4,3,2,1}
    // {1,1,1,1,1}
    // {365,365,365,365,365}
    //
    // Returns: { 1,  2,  3,  4,  5 }
    //
    // These flowers all bloom on January 1st and wilt on December 31st.  Since they all may block each other, you must order them from shortest to tallest.
    //
    // 1)
    // {5,4,3,2,1}
    // {1,5,10,15,20}
    // {4,9,14,19,24}
    //
    // Returns: { 5,  4,  3,  2,  1 }
    //
    // The same set of flowers now bloom all at separate times.  Since they will never block each other, you can order them from tallest to shortest to get the tallest ones as far forward as possible.
    //
    // 2)
    // {5,4,3,2,1}
    // {1,5,10,15,20}
    // {5,10,15,20,25}
    //
    // Returns: { 1,  2,  3,  4,  5 }
    //
    // Although each flower only blocks at most one other, they all must be ordered from shortest to tallest to prevent any blocking from occurring.
    //
    // 3)
    // {5,4,3,2,1}
    // {1,5,10,15,20}
    // {5,10,14,20,25}
    //
    // Returns: { 3,  4,  5,  1,  2 }
    //
    // The difference here is that the third type of flower wilts one day earlier than the blooming of the fourth flower.  Therefore, we can put the flowers of height 3 first, then the flowers of height 4, then height 5, and finally the flowers of height 1 and 2.  Note that we could have also ordered them with height 1 first, but this does not result in the maximum possible height being first in the garden.
    //
    // 4)
    // {1,2,3,4,5,6}
    // {1,3,1,3,1,3}
    // {2,4,2,4,2,4}
    //
    // Returns: { 2,  4,  6,  1,  3,  5 }
    //
    // 5)
    // {3,2,5,4}
    // {1,2,11,10}
    // {4,3,12,13}
    //
    // Returns: { 4,  5,  2,  3 }
    //
    // END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
