import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class GooseInZooDivOne
{
    class Point{
        int x;int y;
        Point(int h,int g)
        {
            x=h;
            y=g;
        }

    }
	public int count(String[] field, int dist)
	{
        int row = field.length;
        int col = field[0].length();
        int[][] x = new int[row][col];

        ArrayList<Point> a[][]=new ArrayList[row][col];

        for (int i = 0; i < row; i++){

            for (int j = 0; j < col; j++) {
                x[i][j] = (field[i].charAt(j)=='v')?1:0;
                a[i][j]=new ArrayList<Point>();
            }

        }
               int dx[]={1,1,-1,-1};
        int dy[]={1,-1,1,-1} ;
        for (int i = 0; i < row; i++) {
            for (int j = 0; j < col; j++) {
                 if(x[i][j]==1)
                 {
                     for(int p=1;p<=dist;p++){
                       for(int k=0;k<=p;k++)
                       {
                             for(int u=0;u<4;u++){
                           if( !(j+(p-k)*dy[u]==j && (i+k*dx[u])==i))
                                if(i+k*dx[u]>=0 && i+k*dx[u]<row && j+(p-k)*dy[u]>=0 && j+(p-k)*dy[u]<col  && x[i+k*dx[u]][j+(p-k)*dy[u]]==1)
                                {
                                    a[i][j].add(new Point(i+k*dx[u],j+(p-k)*dy[u]));
                                    a[i+k*dx[u]][j+(p-k)*dy[u]].add(new Point(i,j));
                                }

                             }

                       }
                     }
                 }
            }
        }
        int visited[][]=new int[row][col];
         long odd=1;long even=1;
        for(int i=0;i<row;i++)
        {
            for(int j=0;j<col;j++)
            {
                if(visited[i][j]==0 && x[i][j]==1)
                {
                    int members=0;
                    Stack<Point> stack=new Stack<Point>();
                    stack.push(new Point(i,j));
                    visited[i][j]=1;

                    while(!stack.isEmpty())
                    {
                        Point p=stack.pop();
                        members++;
                        for(int k=0;k<a[p.x][p.y].size();k++)
                        {
                            if(visited[a[p.x][p.y].get(k).x][a[p.x][p.y].get(k).y]==0){
                            visited[a[p.x][p.y].get(k).x][a[p.x][p.y].get(k).y]=1;
                            stack.push(new Point(a[p.x][p.y].get(k).x,a[p.x][p.y].get(k).y));
                            }
                        }
                    }
                    if(members%2!=0)
                        odd=((odd%1000000007)*2)%1000000007;
                    else
                        even=((even%1000000007)*2)%1000000007;
                    System.out.println(members);
                }
            }

        }
        System.out.println(odd+" " +even);
        if((even%1000000007*(odd/2)%1000000007)==0)
            return 0;
        return (int) (((even%1000000007*(odd/2)%1000000007)%1000000007-1)%1000000007);

    }
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, int p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + p1);
		System.out.println("]");
		GooseInZooDivOne obj;
		int answer;
		obj = new GooseInZooDivOne();
		long startTime = System.currentTimeMillis();
		answer = obj.count(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		int p2;
		
		// ----- test 0 -----
		p0 = new String[]{"vvv"};
		p1 = 0;
		p2 = 3;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"."};
		p1 = 100;
		p2 = 0;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 3 -----
		p0 = new String[]{"v.v..................v............................",".v......v..................v.....................v","..v.....v....v.........v...............v......v...",".........vvv...vv.v.........v.v..................v",".....v..........v......v..v...v.......v...........","...................vv...............v.v..v.v..v...",".v.vv.................v..............v............","..vv.......v...vv.v............vv.....v.....v.....","....v..........v....v........v.......v.v.v........",".v.......v.............v.v..........vv......v.....","....v.v.......v........v.....v.................v..","....v..v..v.v..............v.v.v....v..........v..","..........v...v...................v..............v","..v........v..........................v....v..v...","....................v..v.........vv........v......","..v......v...............................v.v......","..v.v..............v........v...............vv.vv.","...vv......v...............v.v..............v.....","............................v..v.............." +
				"...v",".v.............v.......v..........................","......v...v........................v..............",".........v.....v..............vv..................","................v..v..v.........v....v.......v....","........v.....v.............v......v.v............","...........v....................v.v....v.v.v...v..","...........v......................v...v...........","..........vv...........v.v.....................v..",".....................v......v............v...v....",".....vv..........................vv.v.....v.v.....",".vv.......v...............v.......v..v.....v......","............v................v..........v....v....","................vv...v............................","................v...........v........v...v....v...","..v...v...v.............v...v........v....v..v....","......v..v.......v........v..v....vv..............","...........v..........v........v.v................","v.v......v................v....................v..",".v........v............................." +
				"...v......","............................v...v.......v.........","........................vv.v..............v...vv..",".......................vv........v.............v..","...v.............v.........................v......","....v......vv...........................v.........","....vv....v................v...vv..............v..","..................................................","vv........v...v..v.....v..v..................v....",".........v..............v.vv.v.............v......",".......v.....v......v...............v.............","..v..................v................v....v......",".....v.....v.....................v.v......v......."};
		p1 = 3;
		p2 = 898961330;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Crow Keith is looking at the goose cage in the zoo.
	// The bottom of the cage is divided into a grid of square cells.
	// There are some birds sitting on those cells (with at most one bird per cell).
	// Some of them are geese and all the others are ducks.
	// 
	// Keith wants to know which birds are geese.
	// He knows the following facts about them:
	// 
	// There is at least one goose in the cage.
	// The number of geese is even.
	// Each bird within Manhattan distance dist of any goose is also a goose.
	// 
	//  
	// You are given a String[] field and the int dist.
	// The array field describes the bottom of the cage.
	// Each character of each element of field describes one of the cells.
	// The meaning of individual characters follows.
	// 
	// The character 'v' represents a cell that contains a bird.
	// The character '.' represents an empty cell.
	// 
	// 
	// Return the number of possible sets of geese in the cage, modulo 1,000,000,007.
	// Note that for some of the test cases there can be no possible sets of geese.
	// 
	// DEFINITION
	// Class:GooseInZooDivOne
	// Method:count
	// Parameters:String[], int
	// Returns:int
	// Method signature:int count(String[] field, int dist)
	// 
	// 
	// NOTES
	// -The Manhattan distance between cells (a,b) and (c,d) is |a-c| + |b-d|, where || denotes absolute value. In words, the Manhattan distance is the smallest number of steps needed to get from one cell to the other, given that in each step you can move to a cell that shares a side with your current cell.
	// 
	// 
	// CONSTRAINTS
	// -field will contain between 1 and 50 elements, inclusive.
	// -Each element of field will contain between 1 and 50 characters, inclusive.
	// -Each element of field will contain the same number of characters.
	// -Each character of each element of field will be 'v' or '.'.
	// -dist will be between 0 and 100, inclusive.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// {"vvv"}
	// 0
	// 
	// Returns: 3
	// 
	// There are three possible sets of positions of geese: "ggd", "gdg", or "dgg" ('g' are geese and 'd' are ducks).
	// 
	// 1)
	// {"."}
	// 100
	// 
	// Returns: 0
	// 
	// The number of geese must be positive, but there are no birds in the cage.
	// 
	// 2)
	// {"vvv"}
	// 1
	// 
	// Returns: 0
	// 
	// 
	// 
	// 3)
	// {"v.v..................v............................"
	// ,".v......v..................v.....................v"
	// ,"..v.....v....v.........v...............v......v..."
	// ,".........vvv...vv.v.........v.v..................v"
	// ,".....v..........v......v..v...v.......v..........."
	// ,"...................vv...............v.v..v.v..v..."
	// ,".v.vv.................v..............v............"
	// ,"..vv.......v...vv.v............vv.....v.....v....."
	// ,"....v..........v....v........v.......v.v.v........"
	// ,".v.......v.............v.v..........vv......v....."
	// ,"....v.v.......v........v.....v.................v.."
	// ,"....v..v..v.v..............v.v.v....v..........v.."
	// ,"..........v...v...................v..............v"
	// ,"..v........v..........................v....v..v..."
	// ,"....................v..v.........vv........v......"
	// ,"..v......v...............................v.v......"
	// ,"..v.v..............v........v...............vv.vv."
	// ,"...vv......v...............v.v..............v....."
	// ,"............................v..v.................v"
	// ,".v.............v.......v.........................."
	// ,"......v...v........................v.............."
	// ,".........v.....v..............vv.................."
	// ,"................v..v..v.........v....v.......v...."
	// ,"........v.....v.............v......v.v............"
	// ,"...........v....................v.v....v.v.v...v.."
	// ,"...........v......................v...v..........."
	// ,"..........vv...........v.v.....................v.."
	// ,".....................v......v............v...v...."
	// ,".....vv..........................vv.v.....v.v....."
	// ,".vv.......v...............v.......v..v.....v......"
	// ,"............v................v..........v....v...."
	// ,"................vv...v............................"
	// ,"................v...........v........v...v....v..."
	// ,"..v...v...v.............v...v........v....v..v...."
	// ,"......v..v.......v........v..v....vv.............."
	// ,"...........v..........v........v.v................"
	// ,"v.v......v................v....................v.."
	// ,".v........v................................v......"
	// ,"............................v...v.......v........."
	// ,"........................vv.v..............v...vv.."
	// ,".......................vv........v.............v.."
	// ,"...v.............v.........................v......"
	// ,"....v......vv...........................v........."
	// ,"....vv....v................v...vv..............v.."
	// ,".................................................."
	// ,"vv........v...v..v.....v..v..................v...."
	// ,".........v..............v.vv.v.............v......"
	// ,".......v.....v......v...............v............."
	// ,"..v..................v................v....v......"
	// ,".....v.....v.....................v.v......v......."}
	// 3
	// 
	// Returns: 898961330
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
