import java.util.Arrays;


public class GroceryBagger
{
	public int minimumBags(int strength, String[] itemType)
	{
	    Arrays.sort(itemType); int count=1;int res=0;
        for(int i=1;i<itemType.length;i++)
        {
            if(itemType[i-1].equals(itemType[i]))
            {
                count++;
                if(i==itemType.length-1){
                    if(count%strength==0)
                        res+=count/strength;
                    else
                        res+=count/strength+1;
                }
            }

                else{
                //System.out.println(count);
                if(i==itemType.length-1){
                    if(count%strength==0)
                        res+=count/strength +1;
                    else
                        res+=count/strength+2;
                }
                else{
                if(count%strength==0)
                    res+=count/strength;
                else
                    res+=count/strength+1;
                }
                count=1;
            }
        }
        if(itemType.length==1)
            return 1;
        else
        return res;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, String[] p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p1[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		GroceryBagger obj;
		int answer;
		obj = new GroceryBagger();
		long startTime = System.currentTimeMillis();
		answer = obj.minimumBags(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		String[] p1;
		int p2;
		
		// ----- test 0 -----
		p0 = 3;
		p1 = new String[]{"TGQYBCTPETXB", "TGQYBCTPETXB", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "TGQYBCTPETXB", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "TGQYBCTPETXB", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "TGQYBCTPETXB", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "ZIUIRQZRDEUHLDQRQMTZZBTG", "YDEUSXZLTAFNVICQINK", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD", "AISRSLIGANJQJFIWSLCLMTODPEFRVEEZKAJRTCALRXFEOYBBD"};
		p2 = 9;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 3;
		p1 = new String[]{"DAIRY","DAIRY","PRODUCE","PRODUCE","PRODUCE","MEAT"};
		p2 = 3;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 10;
		p1 = new String[]{};
		p2 = 0;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 5;
		p1 = new String[]{"CANNED","CANNED","PRODUCE","DAIRY","MEAT","BREAD","HOUSEHOLD","PRODUCE","FROZEN","PRODUCE","DAIRY"};
		p2 = 7;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 2;
		p1 = new String[]{"CANNED","CANNED","PRODUCE","DAIRY","MEAT","BREAD","HOUSEHOLD","PRODUCE","FROZEN","PRODUCE","DAIRY"};
		p2 = 8;
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// You have just begun working as a grocery bagger at the local TopGrocer food store.  Your job is to place all of a customer's items into bags, so they can be carried from the store.  Your manager has instructed you to use as few bags as possible, to minimize the store's overall cost.  However, for the customer's convenience, you are instructed that only items of the same type can be placed in the same bag.  For instance, a produce item can be bagged with any other produce items, but not with dairy items.
	// 
	// You are given a String[] itemType indicating the type of each item that needs to be bagged.  You are also given an int strength indicating the maximum number of items that can be placed in each bag.  You are to return an int indicating the minimum number of bags required to package the customer's items.
	// 
	// 
	// DEFINITION
	// Class:GroceryBagger
	// Method:minimumBags
	// Parameters:int, String[]
	// Returns:int
	// Method signature:int minimumBags(int strength, String[] itemType)
	// 
	// 
	// CONSTRAINTS
	// -strength will be between 1 and 50, inclusive.
	// -itemType will contain between 0 and 50 elements, inclusive.
	// -Each element of itemType will contain between 1 and 50 characters, inclusive.
	// -Each element of itemType will contain only the characters 'A'-'Z'.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// 2
	// {"DAIRY",
	//  "DAIRY",
	//  "PRODUCE",
	//  "PRODUCE",
	//  "PRODUCE",
	//  "MEAT"}
	// 
	// Returns: 4
	// 
	// Here, you have six items.  You could put two items in each bag, but you would have to mix item types.  The single meat item must get its own bag.  The two dairy items fit in one bag.  The three produce items will require two bags.
	// 
	// 1)
	// 3
	// {"DAIRY",
	//  "DAIRY",
	//  "PRODUCE",
	//  "PRODUCE",
	//  "PRODUCE",
	//  "MEAT"}
	// 
	// Returns: 3
	// 
	// Similar to above, but now we have stronger bags.  Note again, though, that if we were allowed to mix item types, we could get away with only 2 bags.  But since item types cannot be mixed, we need 3 bags.
	// 
	// 2)
	// 10
	// {}
	// 
	// Returns: 0
	// 
	// The bags are really strong, but we didn't buy anything.
	// 
	// 3)
	// 5
	// {"CANNED",   "CANNED",  "PRODUCE",
	//  "DAIRY",    "MEAT",    "BREAD",
	//  "HOUSEHOLD","PRODUCE", "FROZEN",
	//  "PRODUCE", "DAIRY"}
	// 
	// Returns: 7
	// 
	// Notice that a customer doesn't necessarily pay for the items in any particular order, but the bagger still has to be responsible for sorting them out.  In this case, though, one bag for each item type suffices.
	// 
	// 4)
	// 2
	// {"CANNED",   "CANNED",  "PRODUCE",
	//  "DAIRY",    "MEAT",    "BREAD",
	//  "HOUSEHOLD","PRODUCE", "FROZEN",
	//  "PRODUCE", "DAIRY"}
	// 
	// Returns: 8
	// 
	// As above, but our produce requires two bags now.
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
