import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class NewArenaPassword
{
    public int minChange(String oldPassword, int K)
	{

        int l=oldPassword.length();

        int ans=0;
        for(int i=0;i<K && i<l-K;i++)
        {
            int []count=new int[26];
            int rep=0;
            for(int j=i;j<l;j+=l-K){
               count[oldPassword.charAt(j)-'a']++;
            rep++;
            }

        int max=0;
        for(int p=0;p<26;p++)
        {
            if(max<count[p])
                max=count[p];
        }

        ans+=rep-max;
        }
        return ans;
    }

    // BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, int p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + p1);
		System.out.println("]");
		NewArenaPassword obj;
		int answer;
		obj = new NewArenaPassword();
		long startTime = System.currentTimeMillis();
		answer = obj.minChange(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		int p1;
		int p2;
        // ----- test 2 -----
        p0 = "loool";
        p1 = 3;
        p2 = 1;
        all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
        // ------------------

        // ----- test 0 -----
		p0 = "topcoderopen";
		p1 = 5;
		p2 = 3;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "puyopuyo";
		p1 = 4;
		p2 = 0;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		

		// ----- test 3 -----
		p0 = "arena";
		p1 = 5;
		p2 = 0;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "aabb";
		p1 = 3;
		p2 = 2;
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
        // ----- test 4 -----
        p0 = "amavckdkz";
        p1 = 7;
        p2 = 5;
        all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
        // ------------------

		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// You are a huge fan of an online programming contest called SRM (Special Round Match). To participate in an SRM contest, you must first download an applet called Arena, log in to the Arena by entering your username and password, and start competing.
	// 
	// Recently, to avoid hackers' attacks on the Arena, SRM imposes a new rule for the users' passwords. From now on, the first K characters of each user's password must match its last K characters. In this way, if someone enters a password with different first and last K characters repeatedly, it can be considered an attack from hackers.
	// 
	// However, you love your old password and do not want to change many characters from it. You are given a String oldPassword representing your old password, and an int K. Return the minimum number of characters of oldPassword that must be changed so that the string containing the first K characters of oldPassword is equal to the string containing the last K characters of oldPassword.
	// 
	// DEFINITION
	// Class:NewArenaPassword
	// Method:minChange
	// Parameters:String, int
	// Returns:int
	// Method signature:int minChange(String oldPassword, int K)
	// 
	// 
	// CONSTRAINTS
	// -oldPassword will contain between 1 and 50 characters, inclusive.
	// -Each character of oldPassword will be a lowercase letter 'a' - 'z'.
	// -K will be between 1 and the number of characters of oldPassword, inclusive.
	// 
	// 
	// EXAMPLES
	// 
	// 0)
	// "topcoderopen"
	// 5
	// 
	// Returns: 3
	// 
	// A possible solution is changing your password into "topcndetopcn". To do this, you must change the 4th, 7th, and 10th characters (0-based) of "topcoderopen".
	// 
	// 1)
	// "puyopuyo"
	// 4
	// 
	// Returns: 0
	// 
	// Your old password already satisfies the new rule.
	// 
	// 2)
	// "loool"
	// 3
	// 
	// Returns: 1
	// 
	// The first and the last K characters can overlap. In this case, the only optimal solution is to change your password into "lolol".
	// 
	// 3)
	// "arena"
	// 5
	// 
	// Returns: 0
	// 
	// 
	// 
	// 4)
	// "amavckdkz"
	// 7
	// 
	// Returns: 5
	// 
	// 
	// 
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
