public class OrderedNim
{
	public String winner(int[] layout)
	{
        String player=  "Alice";
		                         String winner="Alice";
    for(int i=layout.length-1;i>=0;)
    {
        if(player!=winner)
        {
            if(layout[i]>1)
            {
                layout[i]=1;
            }
            else
            {
                i--;
                if(player.equals("Alice"))
                    winner="Bob";
                else
                    winner=  "Alice";
            }
        }
        else
        i--;

        if(player.equals("Alice"))
            player="Bob";
        else
            player=  "Alice";

    }
        return winner;
    }
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, boolean hasAnswer, String p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}");
		System.out.println("]");
		OrderedNim obj;
		String answer;
		obj = new OrderedNim();
		long startTime = System.currentTimeMillis();
		answer = obj.winner(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p1 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p1);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;

		int[] p0;
		String p1;

		// ----- test 0 -----
		p0 = new int[]{5};
		p1 = "Alice";
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------

		// ----- test 1 -----
		p0 = new int[]{1,2};
		p1 = "Bob";
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------

		// ----- test 2 -----
		p0 = new int[]{2,1};
		p1 = "Alice";
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------

		// ----- test 3 -----
		p0 = new int[]{10,9,8,7,6,5,4,3,2,1};
		p1 = "Alice";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------

		// ----- test 4 -----
		p0 = new int[]{1,1,1,1};
		p1 = "Bob";
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------

		// ----- test 5 -----
		p0 = new int[]{1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1};
		p1 = "Alice";
		all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
	// ------------------

		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// PROBLEM STATEMENT
	// Nim is a game in which two players take turns removing stones from heaps.  On each turn, a player must choose a single heap and remove one or more stones from that heap.  The player who takes the last stone wins.
	//
	// Alice and Bob are bored with playing Nim over and over again, so they've decided to create a new variation called Ordered Nim.  Ordered Nim differs from regular Nim in the following way.  The heaps are numbered 0 through n-1 (where n is the number of heaps), and a player can only remove stones from a heap if all the lower-numbered heaps are empty.
	//
	// You are given a int[] layout, where the i-th element (0-indexed) is the number of stones in heap i at the beginning of the game.  Alice will take the first turn.  Determine who will win the game, assuming both players play optimally.  Return "Alice" if Alice will win, or "Bob" if Bob will win (all quotes for clarity).
	//
	// DEFINITION
	// Class:OrderedNim
	// Method:winner
	// Parameters:int[]
	// Returns:String
	// Method signature:String winner(int[] layout)
	//
	//
	// CONSTRAINTS
	// -layout will contain between 1 and 50 elements, inclusive.
	// -Each element of layout will be between 1 and 1000000000, inclusive.
	//
	//
	// EXAMPLES
	//
	// 0)
	// {5}
	//
	// Returns: "Alice"
	//
	// Alice takes all 5 stones and wins.
	//
	// 1)
	// {1,2}
	//
	// Returns: "Bob"
	//
	// According to the rules of the game, Alice is not allowed to take stones from heap 1 because heap 0 is not empty.  Her only option is to take the one stone from heap 0.  Heap 0 will then be empty, so Bob can take both stones from heap 1 to win the game.
	//
	// 2)
	// {2,1}
	//
	// Returns: "Alice"
	//
	//
	//
	// 3)
	// {10,9,8,7,6,5,4,3,2,1}
	//
	// Returns: "Alice"
	//
	//
	//
	// 4)
	// {1,1,1,1}
	//
	// Returns: "Bob"
	//
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
